// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrwqixzprldwxjpplxoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyd3FpeHpwcmxkd3hqcHBseG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NTMyNTgsImV4cCI6MjA2MTAyOTI1OH0.n9_1tMkSQqxlbFbg4bD0ck4zkh-bYTdOVBLeF493x8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);